spring:
  application:
    name: blog
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useTimezone=true&serverTimezone=UTC
    username: developer
    password: 1234567
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
    show-sql: false
    open-in-view: false
  security:
    jwt:
      secret-key: 57cr37
      expire-length: 3600000
logging:
  level:
    org.springframework.web.cors: ERROR